# -*- coding: utf-8 -*-
# @Time : 2022/5/2 19:44
# @Author : Vincent Vic
# @File : constant.py
# @Software: PyCharm

ADMIN_TOKEN_KEY_REDIS = 'ADMIN_TOKEN_KEY_REDIS_'
ADMIN_UID_KEY_REDIS = 'ADMIN_UID_KEY_REDIS_'
ADMIN_LOG_UID_KEY_REDIS = 'ADMIN_LOG_UID_KEY_REDIS_'

API_TOKEN_KEY_REDIS = 'API_TOKEN_KEY_REDIS_'
API_UID_KEY_REDIS = 'API_UID_KEY_REDIS_'
